import { z } from "zod";
import { Id, Microcredits, Ts } from "./primitives";

export const RunEventType = z.enum([
  "run.started",
  "run.paused",
  "run.resumed",
  "run.cancelled",
  "run.completed",
  "run.failed",
  "coworker.message",
  "user.message",
  "coworker.question",
  "trace.observed",
  "trace.decided",
  "trace.considered",
  "plan.drafted",
  "plan.approved",
  "plan.amended",
  "step.ready",
  "step.started",
  "step.completed",
  "step.failed",
  "step.blocked",
  "step.retrying",
  "step.skipped",
  "research.query",
  "research.evidence",
  "capability.gap_detected",
  "capability.spec_written",
  "capability.build_started",
  "capability.build_output",
  "capability.gate_started",
  "capability.gate_passed",
  "capability.gate_failed",
  "capability.repair_started",
  "capability.repair_succeeded",
  "capability.repair_exhausted",
  "capability.approval_requested",
  "capability.installed",
  "capability.rejected",
  "capability.invoked",
  "capability.returned",
  "artifact.declared",
  "artifact.drafting",
  "artifact.version_created",
  "artifact.ready",
  "artifact.published",
  "artifact.failed",
  "approval.requested",
  "approval.granted",
  "approval.denied",
  "approval.expired",
  "action.proposed",
  "action.executed",
  "action.failed",
  "cost.reserved",
  "cost.consumed",
  "cost.ceiling_warning",
  "cost.ceiling_stop",
  "cost.settled",
  "system.warning",
  "system.error",
  "system.degraded",
]);

export const EventChannel = z.enum([
  "narrative",
  "trace",
  "plan",
  "capability",
  "artifact",
  "approval",
  "cost",
  "system",
]);

export const RunEvent = z.object({
  id: Id,
  seq: z.number().int().positive(),
  runId: Id,
  assignmentId: Id,
  orgId: Id,
  ts: Ts,
  type: RunEventType,
  channel: EventChannel,
  level: z.enum(["info", "warn", "error"]).default("info"),
  visibility: z.enum(["user", "audit", "internal"]).default("user"),
  summary: z.string().min(1).max(280),
  detail: z.unknown().optional(),
  refs: z
    .object({
      stepId: Id.optional(),
      milestoneId: Id.optional(),
      capabilityId: Id.optional(),
      capabilityVersionId: Id.optional(),
      artifactId: Id.optional(),
      artifactVersionId: Id.optional(),
      approvalId: Id.optional(),
      evidenceIds: z.array(Id).optional(),
      externalActionId: Id.optional(),
    })
    .default({}),
  cost: z
    .object({
      microcredits: Microcredits,
      provider: z.enum(["openai", "codex", "octen", "composio", "sandbox", "storage"]),
      units: z.record(z.string(), z.number()),
    })
    .optional(),
});

export type RunEventType = z.infer<typeof RunEventType>;
export type EventChannel = z.infer<typeof EventChannel>;
export type RunEvent = z.infer<typeof RunEvent>;
