import type { EventChannel, RunEventType } from "@forge/contracts";

const TYPE_CHANNEL: Record<RunEventType, EventChannel> = {
  "run.started": "plan",
  "run.paused": "plan",
  "run.resumed": "plan",
  "run.cancelled": "plan",
  "run.completed": "plan",
  "run.failed": "plan",
  "coworker.message": "narrative",
  "user.message": "narrative",
  "coworker.question": "narrative",
  "trace.observed": "trace",
  "trace.decided": "trace",
  "trace.considered": "trace",
  "plan.drafted": "plan",
  "plan.approved": "plan",
  "plan.amended": "plan",
  "step.ready": "plan",
  "step.started": "plan",
  "step.completed": "plan",
  "step.failed": "plan",
  "step.blocked": "plan",
  "step.retrying": "plan",
  "step.skipped": "plan",
  "research.query": "trace",
  "research.evidence": "trace",
  "capability.gap_detected": "capability",
  "capability.spec_written": "capability",
  "capability.build_started": "capability",
  "capability.build_output": "capability",
  "capability.gate_started": "capability",
  "capability.gate_passed": "capability",
  "capability.gate_failed": "capability",
  "capability.repair_started": "capability",
  "capability.repair_succeeded": "capability",
  "capability.repair_exhausted": "capability",
  "capability.approval_requested": "capability",
  "capability.installed": "capability",
  "capability.rejected": "capability",
  "capability.invoked": "capability",
  "capability.returned": "capability",
  "artifact.declared": "artifact",
  "artifact.drafting": "artifact",
  "artifact.version_created": "artifact",
  "artifact.ready": "artifact",
  "artifact.published": "artifact",
  "artifact.failed": "artifact",
  "approval.requested": "approval",
  "approval.granted": "approval",
  "approval.denied": "approval",
  "approval.expired": "approval",
  "action.proposed": "approval",
  "action.executed": "approval",
  "action.failed": "approval",
  "cost.reserved": "cost",
  "cost.consumed": "cost",
  "cost.ceiling_warning": "cost",
  "cost.ceiling_stop": "cost",
  "cost.settled": "cost",
  "system.warning": "system",
  "system.error": "system",
  "system.degraded": "system",
};

export function channelFor(type: RunEventType): EventChannel {
  return TYPE_CHANNEL[type];
}
